mass_percentage = "1/6"
print("On the Moon, you would weigh about %s of your weight on Earth" % mass_percentage)


mass_percentage = "1/6"
print("On the Moon, you would weigh about {} of your weight on Earth".format(mass_percentage))



#prueba
nombre = "alejandro mejia"
edad = "34"
porcentaje = "60%"
print("Mucho gusto soy {0}, tengo {1} años con el del curso aprobado".format(nombre,edad))

print(f"On the Moon, you would weigh about {round(100/6, 1)}% of your weight on Earth")
print("Mucho gusto soy {0}, tengo {1} años con el {2} del curso aprobado".format(nombre,edad,porcentaje))



